import typing
from enum import IntFlag, auto
from BaseClasses import ItemClassification, Item

def mvm_data_to_ap_id():
    ""

def ap_id_to_mvm_data():
    ""

class MvMItem(Item):
    game: str = "Team Fortress 2 Mann Vs. Machine"

class Group(IntFlag):
    base = auto()
    credits = auto()
    upgrades = auto()
    tf_class = auto()
    mvm_class = auto()
    shop = auto()
    mvm_map = auto()
    mission = auto()
    wave = auto()
    weapon = auto()
    weapon_slot = auto()
    canteen = auto()
    robots = auto()
    traps = auto()


credits_table = {
    'Crash Course Starting Credits':                    ('Credits', True, "", ""),
    'Crash Course Wave 1 Random Heavy':                 ('Credits', True, "", ""),
    'Crash Course Wave 1 Scouts':                       ('Credits', True, "", ""),
    'Crash Course Wave 1 Combos':                       ('Credits', True, "", ""),
    'Crash Course Wave 1 Completed':                    ('Credits', True, "", ""),
    'Crash Course Wave 1 50 Bonus':                     ('Credits', True, "", ""),
    'Crash Course Wave 1 100 Bonus':                    ('Credits', True, "", ""),
    'Crash Course Wave 2 Pyro Heavy Combos':            ('Credits', True, "", ""),
    'Crash Course Wave 2 Giant Pyro Combos':            ('Credits', True, "", ""),
    'Crash Course Wave 2 Completed':                    ('Credits', True, "", ""),
    'Crash Course Wave 2 50 Bonus':                     ('Credits', True, "", ""),
    'Crash Course Wave 2 100 Bonus':                    ('Credits', True, "", ""),
    'Crash Course Wave 3 Tank':                         ('Credits', True, "", ""),
    'Crash Course Wave 3 Completed':                    ('Credits', True, "", ""),
    'Crash Course Wave 3 50 Bonus':                     ('Credits', True, "", ""),
    'Crash Course Wave 3 100 Bonus':                    ('Credits', True, "", ""),
    'Crash Course Wave 4 Scouts':                       ('Credits', True, "", ""),
    'Crash Course Wave 4 Soldiers':                     ('Credits', True, "", ""),
    'Crash Course Wave 4 Demomen':                      ('Credits', True, "", ""),
    'Crash Course Wave 4 Giant Demomen':                ('Credits', True, "", ""),
    'Crash Course Wave 4 Completed':                    ('Credits', True, "", ""),
    'Crash Course Wave 4 50 Bonus':                     ('Credits', True, "", ""),
    'Crash Course Wave 4 100 Bonus':                    ('Credits', True, "", ""),
    'Crash Course Wave 5 Combos':                       ('Credits', True, "", ""),
    'Crash Course Wave 5 Tank':                         ('Credits', True, "", ""),
    'Crash Course Wave 5 Completed':                    ('Credits', True, "", ""),
    'Crash Course Wave 5 50 Bonus':                     ('Credits', True, "", ""),
    'Crash Course Wave 5 100 Bonus':                    ('Credits', True, "", ""),
    'Crash Course Wave 6 Scouts':                       ('Credits', True, "", ""),
    'Crash Course Wave 6 Giant Demomen':                ('Credits', True, "", ""),
    'Crash Course Wave 6 Giant Heavy Combos':           ('Credits', True, "", ""),
    'Crash Course Wave 6 Giant Pyros':                  ('Credits', True, "", ""),
    'Crash Course Wave 6 Tank':                         ('Credits', True, "", ""),
    'Crash Course Mission Complete':                    ('Credits', True, "", ""),
}
#   Name                                                
upgrades_table = {
    'Blast Resistance':                                 ('Item', True, "", {'alias': ('All Class', 3), 'progressive': 3}),
    'Bullet Resistance':                                ('Item', True, "", {}),
    'Movement Speed':                                   ('Item', True, "", {}),
    'Health Regen':                                     ('Item', True, "", {}),
    'Jump Height':                                      ('Item', True, "", {}),
    'Fire Resistance':                                  ('Item', True, "", {}),
    'Crit Resistance':                                  ('Item', True, "", {}),
    'Metal Regen':                                      ('Item', True, "", {'alias': ('Engineer', 5), 'progressive': 5}),
    'Damage (Scout)':                                   ('Item', True, "", {}),
    'Damage (Soldier)':                                 ('Item', True, "", {}),
    'Damage (Pyro)':                                    ('Item', True, "", {}),
    'Damage (Demoman)':                                 ('Item', True, "", {}),
    'Damage (Sniper)':                                  ('Item', True, "", {}),
    'Damage (Demoknight)':                              ('Item', True, "", {}),
    'Clip Size (+2 Clip Soldier)':                      ('Item', True, "", {}),
    'Clip Size (+2 Clip Grenade)':                      ('Item', True, "", {}),
    'Clip Size (+2 Clip Sticky)':                       ('Item', True, "", {}),
    'Clip Size (+2 Clip Size Crossbow)':                ('Item', True, "", ()),
    'Clip Size (50% Clip)':                             ('Item', True, "", {}),
    'Clip Size (200 Credits 50% Clip)':                 ('Item', True, "", {}),
    'Projectile Penetration (Heavy)':                   ('Item', True, "", {}),
    'Projectile Penetration (400)':                     ('Item', True, "", {}),
    'Projectile Penetration (200)':                     ('Item', True, "", {}),
    'Ammo Capacity (250)':                              ('Item', True, "", {}),
    'Ammo Capacity (125)':                              ('Item', True, "", {}),
    }

class_table = {
    'Scout':                                            ('', True, "", {}),
    'Soldier':                                          ('', True, "", {}),
    'Pyro':                                             ('', True, "", {}),
    'Demoman':                                          ('', True, "", {}),
    'Heavy':                                            ('', True, "", {}),
    'Engineer':                                         ('', True, "", {}),
    'Medic':                                            ('', True, "", {}),
    'Sniper':                                           ('', True, "", {}),
    'Spy':                                              ('', True, "", {}),
}

weapon_table = {
    'Scattergun':                                       ('', True, "", {}),
    'Force-A-Nature':                                   ('', True, "", {}),
    'Soda Popper':                                      ('', True, "", {}),
    'Baby Face\'s Blaster':                             ('', True, "", {}),
    'Shortstop':                                        ('', True, "", {}),
    'Backscatter':                                      ('', True, "", {}),
    'Pistol':                                           ('', True, "", {}),
    'Lugermorph':                                       ('', True, "", {}),
    'Mad Milk':                                         ('', True, "", {}),
    'Mutated Milk':                                     ('', True, "", {}),
    'BONK! Atomic Punch':                               ('', True, "", {}),
    'Crit-a-Cola':                                      ('', True, "", {}),
    'Pretty Boy\'s Pocket Pistol':                      ('', True, "", {}),
    'Winger':                                           ('', True, "", {}),
    'Flying Guillotine':                                ('', True, "", {}),
    'C.A.P.P.E.R.':                                     ('', True, "", {}),
    'Bat':                                              ('', True, "", {}),
    'Frying Pan':                                       ('', True, "", {}),
    'Golden Frying Pan':                                ('', True, "", {}),
    'Saxxy':                                            ('', True, "", {}),
    'Conscientious Objector':                           ('', True, "", {}),
    'Freedom Staff':                                    ('', True, "", {}),
    'Bat Outta Hell':                                   ('', True, "", {}),
    'Memory Maker':                                     ('', True, "", {}),
    'Ham Shank':                                        ('', True, "", {}),
    'Necro Smasher':                                    ('', True, "", {}),
    'Crossing Guard':                                   ('', True, "", {}),
    'Batsaber':                                         ('', True, "", {}),
    'Prinny Machete':                                   ('', True, "", {}),
    'Sandman':                                          ('', True, "", {}),
    'Holy Mackerel':                                    ('', True, "", {}),
    'Unarmed Combat':                                   ('', True, "", {}),
    'Boston Basher':                                    ('', True, "", {}),
    'Three-Rune Blade':                                 ('', True, "", {}),
    'Candy Cane':                                       ('', True, "", {}),
    'Sun-on-a-Stick':                                   ('', True, "", {}),
    'Fan O\' War':                                      ('', True, "", {}),
    'Atomizer':                                         ('', True, "", {}),
    'Wrap Assassin':                                    ('', True, "", {}),
    'Rocket Launcher':                                  ('', True, "", {}),
    'Original':                                         ('', True, "", {}),
    'Direct Hit':                                       ('', True, "", {}),
    'Black Box':                                        ('', True, "", {}),
    'Rocket Jumper':                                    ('', True, "", {}),
    'Liberty Launcher':                                 ('', True, "", {}),
    'Cow Mangler 5000':                                 ('', True, "", {}),
    'Beggar\'s Bazooka':                                ('', True, "", {}),
    'Air Strike':                                       ('', True, "", {}),
    'Shotgun':                                          ('', True, "", {}),
    'Reserve Shooter':                                  ('', True, "", {}),
    'Buff Banner':                                      ('', True, "", {}),
    'Gunboats':                                         ('', True, "", {}),
    'Battalion\'s Backup':                              ('', True, "", {}),
    'Concheror':                                        ('', True, "", {}),
    'Manthreads':                                       ('', True, "", {}),
    'Righteous Bison':                                  ('', True, "", {}),
    'B.A.S.E. Jumper':                                  ('', True, "", {}),
    'Panic Attack':                                     ('', True, "", {}),
    'Shovel':                                           ('', True, "", {}),
    'Equalizer':                                        ('', True, "", {}),
    'Pain Train':                                       ('', True, "", {}),
    'Half-Zatoichi':                                    ('', True, "", {}),
    'Disciplinary Action':                              ('', True, "", {}),
    'Market Gardener':                                  ('', True, "", {}),
    'Escape Plan':                                      ('', True, "", {}),
    'Flamethrower':                                     ('', True, "", {}),
    'Rainblower':                                       ('', True, "", {}),
    'Nostromo Napalmer':                                ('', True, "", {}),
    'Backburner':                                       ('', True, "", {}),
    'Degreaser':                                        ('', True, "", {}),
    'Phloginistator':                                   ('', True, "", {}),
    'Dragon\'s Fury':                                   ('', True, "", {}),
    'Flare Gun':                                        ('', True, "", {}),
    'Detonator':                                        ('', True, "", {}),
    'Manmelter':                                        ('', True, "", {}),
    'Scorch Shot':                                      ('', True, "", {}),
    'Thermal Thruster':                                 ('', True, "", {}),
    'Gas Passer':                                       ('', True, "", {}),
    'Fire Axe':                                         ('', True, "", {}),
    'Lollichop':                                        ('', True, "", {}),
    'Axtinguisher':                                     ('', True, "", {}),
    'Postal Pummeler':                                  ('', True, "", {}),
    'Homewrecker':                                      ('', True, "", {}),
    'Maul':                                             ('', True, "", {}),
    'Powerjack':                                        ('', True, "", {}),
    'Back Scratcher':                                   ('', True, "", {}),
    'Sharpened Volcano Fragment':                       ('', True, "", {}),
    'Third Degree':                                     ('', True, "", {}),
    'Neon Annihilator':                                 ('', True, "", {}),
    'Hot Hand':                                         ('', True, "", {}),
    'Grenade Launcher':                                 ('', True, "", {}),
    'Loch-n-Load':                                      ('', True, "", {}),
    'Ali Baba\'s Wee Booties':                          ('', True, "", {}),
    'Bootlegger':                                       ('', True, "", {}),
    'Loose Cannon':                                     ('', True, "", {}),
    'Iron Bomber':                                      ('', True, "", {}),
    'Stickybomb Launcher':                              ('', True, "", {}),
    'Scottish Resistance':                              ('', True, "", {}),
    'Chargin\' Targe':                                  ('', True, "", {}),
    'Sticky Jumper':                                    ('', True, "", {}),
    'Splendid Screen':                                  ('', True, "", {}),
    'Tide Turner':                                      ('', True, "", {}),
    'Quickiebomb Launcher':                             ('', True, "", {}),
    'Bottle':                                           ('', True, "", {}),
    'Scottish Handshake':                               ('', True, "", {}),
    'Eyelander':                                        ('', True, "", {}),
    'Horseless Headless Horseman\'s Headtaker':         ('', True, "", {}),
    'Nessie\'s Nine Iron':                              ('', True, "", {}),                              
    'Scotman\'s Skullcutter':                           ('', True, "", {}),
    'Ullapool Caber':                                   ('', True, "", {}),
    'Claidheamh Mòr':                                   ('', True, "", {}),
    'Persian Persuader':                                ('', True, "", {}),
    'Minigun':                                          ('', True, "", {}),
    'Iron Curtain':                                     ('', True, "", {}),
    'Natascha':                                         ('', True, "", {}),
    'Brass Beast':                                      ('', True, "", {}),
    'Tomislav':                                         ('', True, "", {}),
    'Huo-Long Heater':                                  ('', True, "", {}),
    'Family Business':                                  ('', True, "", {}),
    'Sandvich':                                         ('', True, "", {}),
    'Robo-Sandvich':                                    ('', True, "", {}),
    'Dalokohs Bar':                                     ('', True, "", {}),
    'Fishcake':                                         ('', True, "", {}),
    'Buffalo Steak Sandvich':                           ('', True, "", {}),
    'Second Banana':                                    ('', True, "", {}),
    'Fists':                                            ('', True, "", {}),
    'Apoco-Fists':                                      ('', True, "", {}),
    'Killing Gloves of Boxing':                         ('', True, "", {}),
    'Gloves of Running Urgently':                       ('', True, "", {}),
    'Bread Bite':                                       ('', True, "", {}),
    'Warrior\'s Spirit':                                ('', True, "", {}),
    'Fists of Steel':                                   ('', True, "", {}),
    'Eviction Notice':                                  ('', True, "", {}),
    'Holiday Punch':                                    ('', True, "", {}),
    'Frontier Justice':                                 ('', True, "", {}),
    'Widowmaker':                                       ('', True, "", {}),
    'Pomson 6000':                                      ('', True, "", {}),
    'Rescue Ranger':                                    ('', True, "", {}),
    'Wrangler':                                         ('', True, "", {}),
    'Giger Counter':                                    ('', True, "", {}),
    'Short Circuit':                                    ('', True, "", {}),
    'Wrench':                                           ('', True, "", {}),
    'Golden Wrench':                                    ('', True, "", {}),
    'Gunslinger':                                       ('', True, "", {}),
    'Southern Hospitality':                             ('', True, "", {}),
    'Jag':                                              ('', True, "", {}),
    'Eureka Effect':                                    ('', True, "", {}),
    'Construction PDA':                                 ('', True, "", {}),
    'Destruction PDA':                                  ('', True, "", {}),
    'Syringe Gun':                                      ('', True, "", {}),
    'Blutsauger':                                       ('', True, "", {}),
    'Crusader\'s Crossbow':                             ('', True, "", {}),
    'Overdose':                                         ('', True, "", {}),
    'Medi Gun':                                         ('', True, "", {}),
    'Kritzkrieg':                                       ('', True, "", {}),
    'Quick-Fix':                                        ('', True, "", {}),
    'Vaccinator':                                       ('', True, "", {}),
    'Bonesaw':                                          ('', True, "", {}),
    'Ubersaw':                                          ('', True, "", {}),
    'Vita-Saw':                                         ('', True, "", {}),
    'Amputator':                                        ('', True, "", {}),
    'Solemn Vow':                                       ('', True, "", {}),
    'Sniper Rifle':                                     ('', True, "", {}),
    'AWPer Hand':                                       ('', True, "", {}),
    'Huntsman':                                         ('', True, "", {}),
    'Fortified Compound':                               ('', True, "", {}),
    'Sydney Sleeper':                                   ('', True, "", {}),
    'Bazaar Bargain':                                   ('', True, "", {}),
    'Machina':                                          ('', True, "", {}),
    'Shooting Star':                                    ('', True, "", {}),
    'Hitman\'s Heatmaker':                              ('', True, "", {}),
    'Classic':                                          ('', True, "", {}),
    'SMG':                                              ('', True, "", {}),
    'Cleaner\'s Carbine':                               ('', True, "", {}),
    'Jarate':                                           ('', True, "", {}),
    'Self-Aware Beauty Mark':                           ('', True, "", {}),
    'Razorback':                                        ('', True, "", {}),
    'Darwin\'s Danger Shield':                          ('', True, "", {}),
    'Cozy Camper':                                      ('', True, "", {}),
    'Kukri':                                            ('', True, "", {}),
    'Tribalman\'s Shiv':                                ('', True, "", {}),
    'Bushwacka':                                        ('', True, "", {}),
    'Shahanshah':                                       ('', True, "", {}),
    'Revolver':                                         ('', True, "", {}),
    'Big Kill':                                         ('', True, "", {}),
    'Ambassador':                                       ('', True, "", {}),
    'L\'Etranger':                                      ('', True, "", {}),
    'Enforcer':                                         ('', True, "", {}),
    'Diamondback':                                      ('', True, "", {}),
    'Knife':                                            ('', True, "", {}),
    'Sharp Dresser':                                    ('', True, "", {}),
    'Black Rose':                                       ('', True, "", {}),
    'Your Eternal Reward':                              ('', True, "", {}),
    'Wanga Prick':                                      ('', True, "", {}),
    'Conniver\'s Kunai':                                ('', True, "", {}),
    'Big Earner':                                       ('', True, "", {}),
    'Spy-cicle':                                        ('', True, "", {}),
    'Disguise Kit':                                     ('', True, "", {}),
    'Invisiwatch':                                      ('', True, "", {}),
    'Enthusiast\'s Time Piece':                         ('', True, "", {}),
    'Quäckenbirdt':                                     ('', True, "", {}),
    'Cloak and Dagger':                                 ('', True, "", {}),
    'Dead Ringer':                                      ('', True, "", {}),
    'Sapper':                                           ('', True, "", {}),
    'Ap-Sap':                                           ('', True, "", {}),
    'Snack Attack':                                     ('', True, "", {}),
    'Red Tape Recorder':                                ('', True, "", {}),
}

weapon_slot_table = {
    "Primary":                                          ('', True, "", {}),
    "Secondary":                                        ('', True, "", {}),
    "Melee":                                            ('', True, "", {}),
    "Building":                                         ('', True, "", {}),
    "PDA":                                              ('', True, "", {}),
    "PDA 2":                                            ('', True, "", {}),
}

canteens_table = {
    'Crit':                                             ('', True, "", {}),
    'Uber':                                             ('', True, "", {}),
    'Ammo and Clip':                                    ('', True, "", {}),
    'Recall':                                           ('', True, "", {}),
    'Upgrade':                                          ('', True, "", {}),
}

robots_table = {
    'Scout':                                            ('', True, "", ""),
    'Soldier':                                          ('', True, "", ""),
    'Pyro':                                             ('', True, "", ""),
    'Demoman':                                          ('', True, "", ""),
    'Heavy':                                            ('', True, "", ""),
    'Engineer':                                         ('', True, "", ""),
    'Medic':                                            ('', True, "", ""),
    'Sniper':                                           ('', True, "", ""),
    'Spy':                                              ('', True, "", ""),
    'Tank':                                             ('', True, "", ""),
    'Scout (Melee)':                                    ('', True, "", ""),
    'Scout (Fish)':                                     ('', True, "", ""),
    'Scout (Sun on a Stick)':                           ('', True, "", ""),
    'Bonk! Scout':                                      ('', True, "", ""),
    'Minor League Scout':                               ('', True, "", ""),
    'Hyper League Scout':                               ('', True, "", ""),
    'Scout (Wrap Assassin)':                            ('', True, "", ""),
    'Jumping Scout':                                    ('', True, "", ""),
    'Scout (Slow Fire)':                                ('', True, "", ""),
    'Force-A-Nature Scout':                             ('', True, "", ""),
    'Shortstop Scout':                                  ('', True, "", ""),
    'Giant Scout':                                      ('', True, "", ""),
    'Super Scout':                                      ('', True, "", ""),
    'Force-A-Nature Super Scout':                       ('', True, "", ""),
    'Giant Jumping Sandman':                            ('', True, "", ""),
    'Major League Scout':                               ('', True, "", ""),
    'Armored Sandman Scout':                            ('', True, "", ""),
    'Giant Bonk! Scout':                                ('', True, "", ""),
    'Scout (Melee Gatebot)':                            ('', True, "", ""),
    'Scout (Gatebot)':                                  ('', True, "", ""),
    'Scout (Hard Gatebot)':                             ('', True, "", ""),
    'Force-A-Nature Scout (Gatebot)':                   ('', True, "", ""),
    'Force-A-Nature Scout (Crit Gatebot)':              ('', True, "", ""),
    'Hyper League Scout (Gatebot)':                     ('', True, "", ""),
    'Force-a-Nature Super Scout (Gatebot)':             ('', True, "", ""),
    'Major League':                                     ('', True, "", ""),
    'Buff Soldier':                                     ('', True, "", ""),
    'Extended Buff Soldier':                            ('', True, "", ""),
    'Extended Conch Soldier':                           ('', True, "", ""),
    'Extended Backup Soldier':                          ('', True, "", ""),
    'Blast Soldier':                                    ('', True, "", ""),
    'Black Box Soldier':                                ('', True, "", ""),
    'Giant Soldier':                                    ('', True, "", ""),
    'Giant Charged Soldier':                            ('', True, "", ""),
    'Giant Rapid Fire Soldier':                         ('', True, "", ""),
    'Giant Burst Fire Soldier':                         ('', True, "", ""),
    'Giant Buff Banner Soldier':                        ('', True, "", ""),
    'Giant Concheror Soldier':                          ('', True, "", ""),
    'Giant Battalion Soldier':                          ('', True, "", ""),
    'Giant Black Box Soldier':                          ('', True, "", ""),
    'Giga Burst Fire Soldier':                          ('', True, "", ""),
    'Colonel Barrage':                                  ('', True, "", ""),
    'Giant Blast Soldier':                              ('', True, "", ""),
    'Soldier (Gatebot)':                                ('', True, "", ""),
    'Soldier (Normal Gatebot)':                         ('', True, "", ""),
    'Soldier (Direct Hit Crit Gatebot)':                ('', True, "", ""),
    'Soldier (Hard Gatebot)':                           ('', True, "", ""),
    'Blast Soldier (Gatebot)':                          ('', True, "", ""),
    'Black Box Soldier (Gatebot)':                      ('', True, "", ""),
    'Extended Backup Soldier (Gatebot)':                ('', True, "", ""),
    'Extended Conch Soldier (Gatebot)':                 ('', True, "", ""),
    'Extended Conch Soldier (Crit Gatebot)':            ('', True, "", ""),
    'Major Crits (Gatebot)':                            ('', True, "", ""),
    'Colonel Barrage (Gatebot)':                        ('', True, "", ""),
    'Giant Concheror Soldier (Gatebot)':                ('', True, "", ""),
    'Giant Concheror Soldier (Crit Gatebot)':           ('', True, "", ""),
    'Giant Blast Soldier (Gatebot)':                    ('', True, "", ""),
    'Giant Burst Fire Soldier (Gatebot)':               ('', True, "", ""),
    'Giant Burst Fire Soldier (Crit Gatebot)':          ('', True, "", ""),
    'Giant Black Box Soldier (Gatebot)':                ('', True, "", ""),
    'Giant Soldier (Gatebot)':                          ('', True, "", ""),
    'Giant Rapid Fire Soldier (Gatebot)':               ('', True, "", ""),
    'Giant Rapid Fire Soldier (Crit Gatebot)':          ('', True, "", ""),
    'Giant Rapid Fire Soldier (Reload Gatebot)':        ('', True, "", ""),
    'Seargant Crits':                                   ('', True, "", ""),
    'Major Crits':                                      ('', True, "", ""),
    'Major Crits (Gatebot Boss)':                       ('', True, "", ""),
    'Chief Blast Soldier':                              ('', True, "", ""),
    'Major Crits v2':                                   ('', True, "", ""),
    'Chief Concheror Soldier':                          ('', True, "", ""),
    'Flare Pyro':                                       ('', True, "", ""),
    'Pyro Pusher':                                      ('', True, "", ""),
    'Fast Scorch Shot':                                 ('', True, "", ""),
    'Giant Pyro':                                       ('', True, "", ""),
    'Giant Flare Pyro':                                 ('', True, "", ""),
    'Giant Flare Pyro (Scorch Shot)':                   ('', True, "", ""),
    'Giant Airblast Pyro':                              ('', True, "", ""),
    'Pyro (Gatebot)':                                   ('', True, "", ""),
    'Pyro (Hard Gatebot)':                              ('', True, "", ""),
    'Pyro (Expert Gatebot)':                            ('', True, "", ""),
    'Pyro (Always Fire Gatebot)':                       ('', True, "", ""),
    'Flare Pyro (Gatebot)':                             ('', True, "", ""),
    'Giant Pyro (Always Fire Gatebot)':                 ('', True, "", ""),
    'Giant Pyro (Always Fire Crit Gatebot)':            ('', True, "", ""),
    'Chief Pyro':                                       ('', True, "", ""),
    'Demoknight':                                       ('', True, "", ""),
    'Samurai Demo':                                     ('', True, "", ""),
    'Demoman (Persian Pursuader)':                      ('', True, "", ""),
    'Burst Fire Demo':                                  ('', True, "", ""),
    'Giant Rapid Fire Demoman':                         ('', True, "", ""),
    'Giant Fast Fire Demoman':                          ('', True, "", ""),
    'Giant Demoknight':                                 ('', True, "", ""),
    'Giant Burst Fire Demo':                            ('', True, "", ""),
    'Sentry Buster':                                    ('', True, "", ""),
    'Demoman (Gatebot)':                                ('', True, "", ""),
    'Demoman (Normal Gatebot)':                         ('', True, "", ""),
    'Demoman (Hard Gatebot)':                           ('', True, "", ""),
    'Burst Fire Demo (Gatebot)':                        ('', True, "", ""),
    'Burst Fire Demo (Crit Gatebot)':                   ('', True, "", ""),
    'Giant Burst Fire Demo (Gatebot)':                  ('', True, "", ""),
    'Giant Burst Fire Demo (Crit Gatebot)':             ('', True, "", ""),
    'Giant Rapid Fire Demo Chief':                      ('', True, "", ""),
    'Chief Tavish':                                     ('', True, "", ""),
    'Major Bomber':                                     ('', True, "", ""),
    'Sir Nukesalot':                                    ('', True, "", ""),
    'Steel Gauntlet':                                   ('', True, "", ""),
    'Heavyweight Champ':                                ('', True, "", ""),
    'Heavyweight Champ (Fast)':                         ('', True, "", ""),
    'Heavy Mittens':                                    ('', True, "", ""),
    'Heavy Shotgun':                                    ('', True, "", ""),
    'Steel Gauntlet Pusher':                            ('', True, "", ""),
    'Deflector Heavy':                                  ('', True, "", ""),
    'Giant Heavy':                                      ('', True, "", ""),
    'Giant Deflector Heavy':                            ('', True, "", ""),
    'Giant Shotgun Heavy':                              ('', True, "", ""),
    'Giant Brass Beast Heavy':                          ('', True, "", ""),
    'Giant Natascha Heavy':                             ('', True, "", ""),
    'Giant Heal-on-Kill Heavy':                         ('', True, "", ""),
    'Giant Heater Heavy':                               ('', True, "", ""),
    'Super Heavyweight Champ':                          ('', True, "", ""),
    'Heavy (Gatebot)':                                  ('', True, "", ""),
    'Heavy (Normal Gatebot)':                           ('', True, "", ""),
    'Heavy (Hard Gatebot)':                             ('', True, "", ""),
    'Heavy (Crit Gatebot)':                             ('', True, "", ""),
    'Heavy (Expert Crit Gatebot)':                      ('', True, "", ""),
    'Heavy Shotgun (Gatebot)':                          ('', True, "", ""),
    'Steel Gauntlet (Gatebot)':                         ('', True, "", ""),
    'Steel Gauntlet Pusher (Gatebot)':                  ('', True, "", ""),
    'Steel Gauntlet (Crit Gatebot)':                    ('', True, "", ""),
    'Giant Deflector Heavy (Gatebot)':                  ('', True, "", ""),
    'Giant Heavy (Huo-Long Heater Gatebot)':            ('', True, "", ""),
    'Giant Shotgun Heavy (Gatebot)':                    ('', True, "", ""),
    'Giant Shotgun Heavy (Crit Gatebot)':               ('', True, "", ""),
    'Giant Heal-on-Kill Heavy (Gatebot)':               ('', True, "", ""),
    'Captain Punch':                                    ('', True, "", ""),
    'Chief Heal-on-Kill Heavy':                         ('', True, "", ""),
    'Chief Heal-on-Kill Heavy (Gatebot)':               ('', True, "", ""),
    'Giant Heal-on-Kill Heavy (Boss Gatebot)':          ('', True, "", ""),
    'Engineer (Spawn In With Teleporter)':              ('', True, "", ""),
    'Engineer (Spawn In)':                              ('', True, "", ""),
    'Engineer (Teleport In With Teleporter)':           ('', True, "", ""),
    'Engineer (Teleport In)':                           ('', True, "", ""),
    'Quick Uber Medic':                                 ('', True, "", ""),
    'Big Heal Medic':                                   ('', True, "", ""),
    'Quick-Fix Medic':                                  ('', True, "", ""),
    'Slow Uber Medic':                                  ('', True, "", ""),
    'Medic (Vaccinator Bullet)':                        ('', True, "", ""),
    'Medic (Vaccinator Blast)':                         ('', True, "", ""),
    'Medic (Vaccinator Fire)':                          ('', True, "", ""),
    'Giant Medic':                                      ('', True, "", ""),
    'Giant Medic (Regen)':                              ('', True, "", ""),
    'Razorback Sniper':                                 ('', True, "", ""),
    'Sydney Sniper':                                    ('', True, "", ""),
    'Bowman':                                           ('', True, "", ""),
    'Bowman Rapid Fire':                                ('', True, "", ""),
    'Bowman Rapid Fire (Gatebot)':                      ('', True, "", ""),
}

wave_table = {
    'Crash Course Wave 1':                              ('', True, "", ""),
    'Crash Course Wave 2':                              ('', True, "", ""),
    'Crash Course Wave 3':                              ('', True, "", ""),
    'Crash Course Wave 4':                              ('', True, "", ""),
    'Crash Course Wave 5':                              ('', True, "", ""),
    'Crash Course Wave 6':                              ('', True, "", ""),
}

mission_table = {
    'Crash Course':                                     ('', True, "", ""),
    'Doe\'s Drill':                                     ('', True, "", ""),
    'Mann-euvers':                                      ('', True, "", ""),
    'Benign Infiltration':                              ('', True, "", ""),
    'Big Apple Barricade':                              ('', True, "", ""),
    'Village Vanguard':                                 ('', True, "", ""),
    'Caliginous Caper':                                 ('', True, "", ""),
    'Cave-In':                                          ('', True, "", ""),
    'Quarry':                                           ('', True, "", ""),
    'Doe\'s Doom':                                      ('', True, "", ""),
    'Day of Wreckoning':                                ('', True, "", ""),
    'Mean Machines':                                    ('', True, "", ""),
    'Mann Hunt':                                        ('', True, "", ""),
    'Disk Deletion':                                    ('', True, "", ""),
    'Data Demolition':                                  ('', True, "", ""),
    'Disintegration':                                   ('', True, "", ""),
    'Ctrl + Alt + Destruction':                         ('', True, "", ""),
    'CPU Slaughter':                                    ('', True, "", ""),
    'Machine Massacre':                                 ('', True, "", ""),
    'Mech Mutilation':                                  ('', True, "", ""),
    'Broken Parts':                                     ('', True, "", ""),
    'Bone Shaker':                                      ('', True, "", ""),
    'Empire Escalation':                                ('', True, "", ""),
    'Metro Malice':                                     ('', True, "", ""),
    'Hamlet Hostility':                                 ('', True, "", ""),
    'Bavarian Botbash':                                 ('', True, "", ""),
    'Desperation':                                      ('', True, "", ""),
    'Cataclysm':                                        ('', True, "", ""),
    'Mannslaughter':                                    ('', True, "", ""),
}

map_table = {
    'Coaltown':                                         ('', True, "", ""),
    'Decoy':                                            ('', True, "", ""),
    'Mannworks':                                        ('', True, "", ""),
    'Ghost Town':                                       ('', True, "", ""),
    'Bigrock':                                          ('', True, "", ""),
    'Mannhattan':                                       ('', True, "", ""),
    'Rottenburg':                                       ('', True, "", ""),
}

trap_table = {

}